Repository project-wins/react-wins, pull requests merged in 2024-09, with the labels that each got.

#48 구단 소개, 구단 연혁 페이지 마크업
  src/assets/icons/historyIcon.png
  src/assets/images/aboutImg1.png
  src/assets/images/aboutImg2.png
  src/assets/images/aboutImg3.png
  src/components/About/ClubDescription.tsx
  src/components/About/ClubHistory.tsx
  src/components/About/Description.tsx
  src/components/About/History.tsx
  src/pages/NewsDetail.tsx
  src/pages/PressDetail.tsx
  src/router/index.tsx
  src/styles/about.style.ts
Labels: design

#54 fix: 카카오맵 에러 관련 로직 작성, 서버에서 사용할 env파일 작성
  package-lock.json
  package.json
  src/api/api.ts
  src/assets/images/iksan_map.png
  src/assets/images/map_img.png
  src/components/Location/KakaoMap.tsx
  src/utils/getEnv.ts
Labels: fix

#55 fix: .env파일 전역상수로 구현
  src/api/api.ts
  src/components/Location/KakaoMap.tsx
  src/utils/getEnv.ts
  vite.config.ts
Labels: fix

#41 홈화면 선수갤러리(wiz gallery )레이아웃
  package-lock.json
  package.json
  src/assets/icons/arrow_left.png
  src/assets/icons/arrow_right.png
  src/assets/images/home_title_gallery.png
  src/components/Home/WizGallery.tsx
  src/components/Home/WizGallery/GallerySwiper.tsx
  src/components/Home/WizGallery/GalleryTitle.tsx
  src/components/common/Controller.tsx
  src/data/gallery.json
  src/pages/Home.tsx
  src/types/gallery.d.ts
Labels: design

#57 game/순위기록/팀순위 레이아웃
  src/components/TeamRanking/RankingChart.tsx
  src/components/TeamRanking/RecordBatter.tsx
  src/components/TeamRanking/RecordPicher.tsx
  src/components/TeamRanking/RecordTeam.tsx
  src/components/TeamRanking/WinLose.tsx
  src/components/common/ArticleTitle.tsx
  src/components/common/RankingTab.tsx
  src/pages/TeamRanking.tsx
  src/router/index.tsx
  src/styles/Ranking.style.ts
Labels: design

#59 fix: 프록시 설정
  vite.config.ts
Labels: fix

#63 html문자열 파싱
  package-lock.json
  package.json
  src/components/Media/MediaDetail.tsx
  src/components/Media/MediaItem.tsx
  src/utils/stringParsing.ts
Labels: feat, refactor

#61 더미데이터 추가
  src/data/game/RankPitcherTotal.json
  src/data/game/RankPitcherWin.json
  src/data/game/allGameSchedule.json
  src/data/game/boxscore.json
  src/data/game/daySchedule.json
  src/data/game/monthSchedule.json
  src/data/game/periodTeamRank.json
  src/data/game/rankBatter.json
  src/data/game/rankBatterHr.json
  src/data/game/rankBatterHra.json
  src/data/game/rankBatterTotal.json
  src/data/game/rankBatting.json
  src/data/game/rankCrowd.json
  src/data/game/rankPitcher.json
  src/data/game/rankPitcherEra.json
  src/data/game/rankPitching.json
  src/data/game/rankTeamVs.json
  src/data/game/rankTotalBatter.json
  src/data/game/rankTotalPitcher.json
  src/data/game/teamRankByYear.json
  src/data/game/watchPoint.json
  src/data/main/highlightList.json
  src/data/main/hotIssue.json
  src/data/main/photoList.json
  src/data/main/recentGames.json
  src/data/main/teamRank.json
  src/data/media/newsDetail.json
  src/data/media/newslist.json
  src/data/media/pressDetail.json
  src/data/media/pressList.json
  src/data/player/catcherDetail.json
  src/data/player/catcherList.json
  src/data/player/cheerleader.json
  src/data/player/coachDetail.json
  src/data/player/coachList.json
  src/data/player/infielderDetail.json
  src/data/player/infielderList.json
  src/data/player/outerfielderDetail.json
  src/data/player/outfielderList.json
  src/data/player/pitcherDetail.json
  src/data/player/pitcherList.json
Labels: refactor

#64 미디어리스트 및 미디어상세 api연결
  src/api/api.ts
  src/pages/News.tsx
  src/pages/NewsDetail.tsx
  src/pages/Press.tsx
  src/pages/PressDetail.tsx
Labels: feat

#60 Feature/game/boxscore 마크업 및 레이아웃
  src/components/BoxScore/MainTable.tsx
  src/data/boxScore.json
  src/pages/BoxScore.tsx
  src/router/index.tsx
  src/types/etcgame.d.ts
Labels: design

#71 공통컴포넌트 분리
  src/components/common/Search.tsx
  src/components/common/SearchButton.tsx
  src/components/common/SearchForm.tsx
  src/components/common/Table.tsx
Labels: refactor

#69 Game-관전포인트 페이지 레이아웃 마크업&스타일링
  src/assets/images/watchPointImg1.png
  src/assets/images/watchPointImg2.png
  src/components/Game/WatchPoint/Channel.tsx
  src/components/Game/WatchPoint/Description.tsx
  src/components/Game/WatchPoint/Lineup.tsx
  src/components/Game/WatchPoint/Lineup/PlayerItem.tsx
  src/components/Game/WatchPoint/Lineup/PlayerList.tsx
  src/components/Game/WatchPoint/Lineup/Team.tsx
  src/components/Game/WatchPoint/Pitcher.tsx
  src/components/Game/WatchPoint/Pitcher/Table.tsx
  src/components/Game/WatchPoint/Record.tsx
  src/components/Game/WatchPoint/Record/Body.tsx
  src/components/Game/WatchPoint/Record/Button.tsx
  src/components/Game/WatchPoint/Record/Description.tsx
  src/components/Game/WatchPoint/Record/Header.tsx
  src/components/Game/WatchPoint/Record/Logo.tsx
  src/components/Game/WatchPoint/Record/Table.tsx
  src/components/Game/WatchPoint/Record/Title.tsx
  src/components/Game/WatchPoint/Title.tsx
  src/components/Game/WatchPoint/Weather.tsx
  src/pages/WatchPoint.tsx
  src/router/index.tsx
Labels: design

#75 미디어 페이지 페이지네이션 버튼 연결
  src/components/Media/PaginationButtons.tsx
  src/pages/News.tsx
  src/pages/Press.tsx
Labels: feat

#81 배너 이미지 및 네비게이션 수정
  src/assets/images/banner.png
  src/components/ui/header/gnb/BottomMenu.tsx
  src/components/ui/header/gnb/Nav.tsx
  src/components/ui/header/gnb/TopMenu.tsx
  src/components/ui/main/Banner.tsx
Labels: refactor

#82 홈갤러리 api연결 및 더보기 버튼 연결
  src/components/Home/WizGallery.tsx
  src/components/Home/WizGallery/GallerySwiper.tsx
  src/components/common/Controller.tsx
  src/types/gallery.d.ts
Labels: feat, refactor

#84 응원단 페이지 레이아웃 마크업
  src/components/Cheer/CheerInfo.tsx
  src/components/Cheer/CheerProfile.tsx
  src/pages/Cheer.tsx
  src/router/index.tsx
Labels: design

#74 feat: boxscore 테이블 보드 구현 및 데이터 패칭
  src/components/BoxScore/BoxScoreInfo.tsx
  src/components/BoxScore/BoxTable.tsx
  src/pages/BoxScore.tsx
  src/router/index.tsx
  src/store/actions/useGameStore.ts
  src/store/types/gameStore.d.ts
  src/types/boxScore.d.ts
  src/utils/date.ts
  src/utils/filterBoxScoreData.ts
Labels: feat, design

#76 design: 주소, 버스, 지하철 줄바뀌는거 수정, 색깔 변경
  src/components/Location/KakaoMap.tsx
  src/components/Location/LocationGuide.tsx
  src/pages/Iksan.tsx
  src/pages/Location.tsx
Labels: design

#94 중요구현 외 페이지 구현
  src/components/common/ArticleTitle.tsx
  src/components/ui/header/gnb/TopMenu.tsx
  src/pages/Donation.tsx
  src/pages/Entrance.tsx
  src/pages/Policy.tsx
  src/pages/Store.tsx
  src/router/index.tsx
  src/styles/ImageStyle.style.ts
Labels: design

#96 fix: 데이터 패칭 오류 수정
  src/pages/InfielderDetail.tsx
  src/pages/Outfielder.tsx
  src/pages/OutfielderDetail.tsx
Labels: fix

#91 탭 임시 수정 및 불필요한 정보 삭제
  src/components/ui/header/gnb/BottomMenu.tsx
  src/data/nav.json
Labels: fix, refactor

#95 game-관전포인트 데이터 패칭
  src/components/Game/WatchPoint/Channel.tsx
  src/components/Game/WatchPoint/Lineup.tsx
  src/components/Game/WatchPoint/Lineup/PlayerItem.tsx
  src/components/Game/WatchPoint/Lineup/PlayerList.tsx
  src/components/Game/WatchPoint/Lineup/Team.tsx
  src/components/Game/WatchPoint/Pitcher/Table.tsx
  src/components/Game/WatchPoint/Record.tsx
  src/components/Game/WatchPoint/Record/Body.tsx
  src/components/Game/WatchPoint/Record/Button.tsx
  src/components/Game/WatchPoint/Record/Header.tsx
  src/components/Game/WatchPoint/Record/Logo.tsx
  src/components/Game/WatchPoint/Record/Table.tsx
  src/pages/WatchPoint.tsx
  src/store/actions/useWatchPointStore.ts
  src/store/types/watchPointStore.d.ts
  src/types/watchPoint.d.ts
Labels: feat, design

#97 home-gameSchedule 링크 연결 및 데이터 패칭 진행중
  src/components/Home/Common/Container.tsx
  src/components/Home/Etc/MontlyPlayer.tsx
  src/components/Home/GameSchedule/Parking.tsx
  src/components/Home/GameSchedule/TeamRanking.tsx
  src/store/actions/useHomeStore.ts
  src/store/types/homeStore.d.ts
  src/types/home.d.ts
Labels: feat, design

#100 박스 스코어 데이터 패칭 및 테이블 구현
  src/components/BoxScore/BoxScoreInfo.tsx
  src/components/BoxScore/MainTable.tsx
  src/data/gameHeaders.ts
  src/pages/BoxScore.tsx
  src/store/actions/useGameStore.ts
  src/store/types/gameStore.d.ts
  src/types/boxScore.d.ts
  src/types/etcgame.d.ts
  src/utils/filterBoxScoreData.ts
Labels: feat, fix, design

#101 미디어리스트&플레이어 상세 스켈레톤 마크업
  src/assets/images/playerSkeleton.png
  src/components/Media/MediaItem.tsx
  src/components/Media/SkeletonList.tsx
  src/components/Player/PlayerInfo.tsx
  src/styles/Media.style.ts
  src/styles/Skeleton.style.ts
Labels: design

#102 관중현황 마크업
  src/assets/images/AudienceImg/accrue.png
  src/assets/images/AudienceImg/record.png
  src/components/Audience/AccrueAudience.tsx
  src/components/Audience/AudienceRecord.tsx
  src/pages/Audience.tsx
  src/router/index.tsx
  src/styles/Ranking.style.ts
Labels: design

#106 player radar 차트 마크업 및 데이터 패칭
  package-lock.json
  package.json
  src/components/Player/PlayerChart.tsx
  src/components/Player/PlayerDetail.tsx
  src/store/actions/usePlayerStore.ts
Labels: feat, design

#112 페이지 이동시 스크롤이 최상단으로 이동되도록 구현 및 top 버튼 모든 페이지에 적용
  src/components/ScrollToTop.tsx
  src/components/common/TopButton.tsx
  src/components/ui/footer/Select.tsx
  src/layouts/BasicLayout.tsx
  src/layouts/CommonLayout.tsx
  src/pages/CatcherDetail.tsx
  src/pages/CoachDetail.tsx
  src/pages/InfielderDetail.tsx
  src/pages/OutfielderDetail.tsx
  src/pages/PitcherDetail.tsx
Labels: feat, refactor

#109 home-gameSchedule 데이터 패칭
  src/assets/images/AudienceImg/accrue.png
  src/assets/images/AudienceImg/record.png
  src/assets/images/playerSkeleton.png
  src/components/Audience/AccrueAudience.tsx
  src/components/Audience/AudienceRecord.tsx
  src/components/BoxScore/BoxScoreInfo.tsx
  src/components/BoxScore/MainTable.tsx
  src/components/Home/Article.tsx
  src/components/Home/GameSchedule/RecentMatch/ControllBtn.tsx
  src/components/Home/GameSchedule/RecentMatch/MatchesHeader.tsx
  src/components/Home/GameSchedule/RecentMatch/MatchesInfo.tsx
  src/components/Home/GameSchedule/RecentMatch/RecentMatchItem.tsx
  src/components/Home/GameSchedule/RecentMatch/RecentMatchList.tsx
  src/components/Home/GameSchedule/Video.tsx
  src/components/Media/MediaItem.tsx
  src/components/Media/SkeletonList.tsx
  src/components/Player/PlayerInfo.tsx
  src/data/gameHeaders.ts
  src/pages/Audience.tsx
  src/pages/BoxScore.tsx
  src/router/index.tsx
  src/store/actions/useGameStore.ts
  src/store/actions/useHomeStore.ts
  src/store/types/gameStore.d.ts
  src/store/types/homeStore.d.ts
  src/styles/Media.style.ts
  src/styles/Ranking.style.ts
  src/styles/Skeleton.style.ts
  src/types/boxScore.d.ts
  src/types/etcgame.d.ts
  src/types/home.d.ts
  src/types/recentMatch.d.ts
  src/utils/filterBoxScoreData.ts
Labels: feat, design

#114 gameSchedule 데이터 패칭
  src/components/Home/Article.tsx
  src/components/Home/GameSchedule/RecentMatch/ControllBtn.tsx
  src/components/Home/GameSchedule/RecentMatch/MatchesHeader.tsx
  src/components/Home/GameSchedule/RecentMatch/MatchesInfo.tsx
  src/components/Home/GameSchedule/RecentMatch/RecentMatchItem.tsx
  src/components/Home/GameSchedule/RecentMatch/RecentMatchList.tsx
  src/components/Home/GameSchedule/Video.tsx
  src/store/actions/useHomeStore.ts
  src/store/types/homeStore.d.ts
  src/types/home.d.ts
  src/types/recentMatch.d.ts
Labels: feat

#104 시즌팀순위 차트 마크업 및 api연결
  src/components/Game/TeamRanking/RankingChart.tsx
  src/data/game/periodTeamRank.json
  src/utils/date.ts
Labels: feat, design

#121 tanstack query Box Score 적용
  src/components/BoxScore/BoxScoreInfo.tsx
  src/hooks/useBoxScore.ts
  src/main.tsx
  src/pages/BoxScore.tsx
  src/store/actions/useGameStore.ts
  src/store/types/gameStore.d.ts
Labels: feat

#103 game-관전포인트 데이터패칭
  src/api/api.ts
  src/components/Game/Common/ControllButton.tsx
  src/components/Game/Common/Logo.tsx
  src/components/Game/WatchPoint/Channel.tsx
  src/components/Game/WatchPoint/Description.tsx
  src/components/Game/WatchPoint/Pitcher/Table.tsx
  src/components/Game/WatchPoint/Record.tsx
  src/components/Game/WatchPoint/Record/Body.tsx
  src/components/Game/WatchPoint/Record/Button.tsx
  src/components/Game/WatchPoint/Record/Header.tsx
  src/components/Game/WatchPoint/Record/Table.tsx
  src/components/Game/WatchPoint/Weather.tsx
  src/data/nav.json
  src/pages/WatchPoint.tsx
  src/router/index.tsx
  src/store/actions/useWatchPointStore.ts
  src/store/types/watchPointStore.d.ts
  src/types/watchPoint.d.ts
  src/utils/calculateRatio.ts
Labels: feat, fix

#116 컴포넌트 최적화 작업 진행중
  src/components/Home/Etc/MontlyPlayer.tsx
  src/components/Home/GameSchedule.tsx
  src/components/Home/GameSchedule/RecentMatch/ControllBtn.tsx
  src/components/Home/GameSchedule/RecentMatch/MatchesHeader.tsx
  src/components/Home/GameSchedule/RecentMatch/MatchesInfo.tsx
  src/components/Home/GameSchedule/RecentMatch/RecentMatchItem.tsx
  src/components/Home/GameSchedule/RecentMatch/RecentMatchList.tsx
  src/components/Location/KakaoMap.tsx
  src/components/common/Search.tsx
  src/components/common/SearchButton.tsx
  src/components/common/Select.tsx
  src/components/common/TopButton.tsx
  src/components/ui/footer/Footer.tsx
  src/components/ui/footer/Logo.tsx
  src/components/ui/footer/Nav.tsx
  src/components/ui/footer/Select.tsx
  src/components/ui/footer/Social.tsx
  src/components/ui/header/Header.tsx
  src/components/ui/header/Logo.tsx
  src/components/ui/header/Utils.tsx
  src/components/ui/header/gnb/BottomMenu.tsx
  src/components/ui/header/gnb/Nav.tsx
  src/components/ui/header/gnb/TopMenu.tsx
  src/components/ui/main/Banner.tsx
  src/components/ui/main/Breadcrumb.tsx
  src/components/ui/main/tab/TabList.tsx
  src/hooks/useDetectScroll.tsx
Labels: refactor

#122 game-경기일정 마크업&스타일링
  src/components/Game/Schedule/Broadcast.tsx
  src/components/Game/Schedule/Broadcast/BroadcastItem.tsx
  src/components/Game/Schedule/Broadcast/BroadcastList.tsx
  src/components/Game/Schedule/Broadcast/Tag.tsx
  src/components/Game/Schedule/Calendar.tsx
  src/components/Game/Schedule/Calendar/Body.tsx
  src/components/Game/Schedule/Calendar/Header.tsx
  src/components/Game/Schedule/Calendar/Tab.tsx
  src/components/Game/Schedule/Common/Button.tsx
  src/components/Game/Schedule/Common/Date.tsx
  src/components/Game/Schedule/Common/Logo.tsx
  src/components/Game/Schedule/Common/Score.tsx
  src/components/Game/Schedule/Common/Text.tsx
  src/components/Game/Schedule/HomeTeam.tsx
  src/components/Game/Schedule/ScheduleItem.tsx
  src/components/Game/Schedule/ScheduleList.tsx
  src/components/Game/Schedule/VisitTeam.tsx
  src/pages/Schedule.tsx
  src/router/index.tsx
Labels: design

#123 관전포인트 날씨(풍속) 소수점 단위 수정 및 일부 스타일링 수정
  src/components/Game/WatchPoint/Description.tsx
  src/components/Game/WatchPoint/Lineup/PlayerItem.tsx
  src/components/Game/WatchPoint/Record/Description.tsx
  src/components/Game/WatchPoint/Record/Title.tsx
Labels: fix, design

#127 관전포인트 데이터 패칭 버그 수정
  src/pages/WatchPoint.tsx
Labels: fix

#125 game 경기일정 calendar 구현
  package-lock.json
  package.json
  src/components/Game/Common/ControllButton.tsx
  src/components/Game/Schedule/Broadcast/BroadcastList.tsx
  src/components/Game/Schedule/Calendar.tsx
  src/components/Game/Schedule/Calendar/Body.tsx
  src/components/Game/Schedule/Calendar/Cells.tsx
  src/components/Game/Schedule/Calendar/Days.tsx
  src/components/Game/Schedule/Calendar/Dropdown.tsx
  src/components/Game/Schedule/Calendar/Header.tsx
  src/components/Game/Schedule/Calendar/Result.tsx
  src/components/Game/Schedule/Calendar/Tab.tsx
Labels: feat

#131 feat: player 테이블 로직 변경
  src/components/Player/PlayerDetail.tsx
  src/components/Player/PlayerTableInfo.tsx
  src/data/playerHeaders.ts
  src/types/pitcherRecent.d.ts
  src/utils/fiterPlayerData.ts
Labels: feat

#128 홈화면 비디오 (하이라이트) 마크업 및 api연결
  src/assets/images/home_title_video.png
  src/components/Home/Highlight.tsx
  src/components/Home/Video/Controller.tsx
  src/components/Home/Video/VideoList.tsx
  src/components/Home/Video/ViedoBox.tsx
  src/pages/Home.tsx
  src/styles/Home.style.ts
  src/types/highlight.d.ts
  src/utils/date.ts
Labels: feat, design

#130 vercel404에러 수정
  vercel.json
Labels: fix

#108 관중현황 페이지 관중기록 테이블 API 연동
  src/components/Audience/AccrueAudience.tsx
  src/components/Audience/AudienceRecord.tsx
  src/types/Crowd.d.ts
Labels: feat

#135 feat: playerList 페이지 tanstack query적용 및 한 페이지로 병합
  src/components/Game/BoxScore/BoxScoreInfo.tsx
  src/components/Game/BoxScore/BoxTable.tsx
  src/components/Game/BoxScore/MainTable.tsx
  src/components/Player/PlayerDetail.tsx
  src/components/Player/PlayerInfo.tsx
  src/hooks/useBoxScore.ts
  src/hooks/usePlayer.ts
  src/pages/BoxScore.tsx
  src/pages/Catcher.tsx
  src/pages/Coach.tsx
  src/pages/CoachDetail.tsx
  src/pages/Infielder.tsx
  src/pages/InfielderDetail.tsx
  src/pages/OutfielderDetail.tsx
  src/pages/Pitcher.tsx
  src/pages/PitcherDetail.tsx
  src/pages/PlayerDetailPage.tsx
  src/pages/PlayerPage.tsx
  src/router/index.tsx
  src/store/actions/usePlayerStore.ts
  src/store/types/playerStore.d.ts
Labels: feat, fix

#107 응원단페이지 API 연결
  src/components/Cheer/CheerInfo.tsx
  src/components/Cheer/CheerProfile.tsx
  src/pages/Cheer.tsx
  src/types/cheer.d.ts
Labels: feat

#136 게임-팀순위 테이블 api연결
  src/components/Game/TeamRanking/RecordBatter.tsx
  src/components/Game/TeamRanking/RecordPicher.tsx
  src/components/Game/TeamRanking/RecordTeam.tsx
  src/components/Game/TeamRanking/WinLose.tsx
  src/data/game/rankTeamVs.json
  src/utils/filterData.ts
Labels: feat

#132 game 경기일정 데이터 패칭
  src/components/Game/Schedule/Calendar.tsx
  src/components/Game/Schedule/Calendar/Cells.tsx
  src/components/Game/Schedule/Calendar/Dropdown.tsx
  src/components/Game/Schedule/Calendar/Header.tsx
  src/components/Game/Schedule/Calendar/Tab.tsx
  src/components/Game/Schedule/Common/Date.tsx
  src/components/Game/Schedule/Common/Logo.tsx
  src/components/Game/Schedule/Common/Score.tsx
  src/components/Game/Schedule/Common/Text.tsx
  src/components/Game/Schedule/HomeTeam.tsx
  src/components/Game/Schedule/ScheduleItem.tsx
  src/components/Game/Schedule/ScheduleList.tsx
  src/components/Game/Schedule/Team.tsx
  src/components/Game/Schedule/VisitTeam.tsx
  src/pages/Schedule.tsx
  src/store/actions/useScheduleStore.ts
  src/store/types/scheduleStore.d.ts
  src/types/home.d.ts
  src/types/schedule.d.ts
Labels: feat, fix, refactor

#138 feat: table 데이터 패칭 완료
  src/components/Player/PlayerTableInfo.tsx
  src/store/actions/usePlayerStore.ts
  src/store/types/playerStore.d.ts
Labels: feat

#139 파일 경로변경 및 import 경로 수정
  src/assets/images/blackLogo.svg
  src/assets/images/emblem.svg
  src/assets/images/footerLogo.svg
  src/assets/images/headerBtn.svg
  src/assets/images/whiteLogo.svg
  src/components/Home/Etc/MontlyPlayer.tsx
  src/components/Home/Etc/Store.tsx
  src/components/ui/footer/Logo.tsx
  src/components/ui/header/Logo.tsx
  src/components/ui/header/Utils.tsx
Labels: refactor

#141 refactor: common 로고, 버튼 적용
  src/components/Game/BoxScore/BoxScoreInfo.tsx
Labels: refactor

#143 구단소개 페이지 마크업&스타일링
  src/assets/images/aboutImg4.png
  src/components/About/ClubDescription.tsx
  src/components/About/ClubHistory.tsx
  src/components/About/Description.tsx
  src/components/About/History.tsx
  src/components/About/WideImage.tsx
  src/components/common/Description.tsx
  src/components/common/MainTitle.tsx
  src/components/common/SubTitle.tsx
  src/data/nav.json
  src/layouts/CommonLayout.tsx
  src/pages/About.tsx
  src/router/index.tsx
Labels: fix, design

#144 404에러 재수정
  vercel.json
Labels: fix

#146 tooltip정보 수정
  src/components/Game/TeamRanking/RankingChart.tsx
Labels: fix

#148 fix: 캘린더 스크롤 버그 수정
  src/components/Game/Schedule/Calendar/Cells.tsx
Labels: fix

#149 순위기록 하위탭 수정
  src/components/common/RankingTab.tsx
  src/pages/Audience.tsx
Labels: fix

#152 docs: README.md 수정
  README.md
Labels: docs
